### ISSUE TITLE
Automate post-config

### ISSUE THREAD

**Issue by dmsimard** [rdo-infra/rdo-container-registry#1]
See:
- https://github.com/openshift/openshift-ansible/tree/master/roles/lib_openshift/library
- https://rdo-container-registry.readthedocs.io/en/latest/managing.html

```
- name: oc adm policy add-cluster-role-to-user system:build-strategy-docker ausername
  oc_adm_policy_user:
    user: ausername
    resource_kind: cluster-role
    resource_name: system:build-strategy-docker
    state: present

- name: create project
  oc_project:
    state: present
    name: openshift-ops
    display_name: operations team project
    node_selector:
    -  top=secret
    -  noncustomer=True

- name: create registry serviceaccount
  oc_serviceaccount:
    name: registry
    namespace: default
    secrets:
    - docker-registry-config
    - registry-secret
  register: sa_out

  - name: get secrets of a service account
    oc_serviceaccount_secret:
      state: list
      service_account: builder
      namespace: default
    register: sasecretout

- name: List user's info
  oc_user:
    state: list
    username: johndoe
  register: user_johndoe
```
